###
@host=https://ifconfig.co
@path=country

###
http://ifconfig.co/country

###
{{host}}/{{path}}


###
POST http://pie.dev/post
guid: {{$guid}}
randomInt: {{$randomInt 1 6}}
timestamp: {{$timestamp 0}}
datetime: {{$datetime iso8601}}
localDatetime: {{$localDatetime iso8601}}
processEnv: {{$processEnv HOSTNAME}}

###
{{$randomInt min max}}
{{$timestamp [offset option]}}
{{$datetime rfc1123|iso8601 [offset option]}}
{{$localDatetime rfc1123|iso8601 [offset option]}}
{{$processEnv [%]envVarName}}
{{$dotenv [%]variableName}}
{{$aadToken [new] [public|cn|de|us|ppe] [<domain|tenantId>] [aud:<domain|tenantId>]}}