spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:localhost;DB_CLOSE_ON_EXIT=FALSE
    username: admin
    password:

server:
  port : 18080


camelCase: 
  str: camel case

sample:
  str: abc
  a: 1
  sub:
    b: 2
    list:
      - a
      - b