---
- hosts: localhost
  gather_facts: no
  tasks:
  - name: ping
    ping:
  
  # https://www.ziaconsulting.com/developer-help/ansible-tasks-change-status/
  
  - shell: "echo a"
    register: echo

  - shell: "echo b"
    when: echo.changed