# ansible-playbook flow/condition.yml --extra-vars "foo=a"
# ansible-playbook flow/condition.yml -e "foo=a bar=1"
# Ansible ‘When’ Statement: Check If Variable Is…
# From <https://www.shellhacks.com/ansible-when-variable-is-defined-exists-empty-true/>
---
- hosts: localhost
  gather_facts: no
  vars: 
    items:
      - "one"
      - "two"

  tasks:
  - name: ping with foo
    when: foo is defined
    ping:
  - name: ping without foo
    when: foo is undefined
    ping:
  - name: ping without foo
    when: "{{ 'foo' }} is undefined"
    ping:
  - name: env
    when: lookup('env', 'PATH') != ''
    ping:
  - name: shell
    when: bar|length == 1
    shell: pwd
    register: result
    ignore_errors: true
  - name: output
    when: (foo is defined) and (foo|length > 0)
    debug: var=result.stdout_lines
    ignore_errors: true
  - shell: "echo {{ item }}"
    loop: "{{ items }}"
    when: items.0 == 'one'
    register: echo

  # https://stackoverflow.com/questions/34340562/evaluating-return-code-in-ansible-conditional
  - name: register version check
    shell: echo abc
    register: abc
    failed_when: abc.rc == 2

  # https://phoenixnap.com/kb/ansible-check-if-file-exists
  - name: Check if a File Exists 1
    stat:
      path: condition.yml
    register: register_name
  - name: Check if a File Exists 2
    debug:
      msg: "The file or directory exists"
    when: register_name.stat.exists