---
- hosts: localhost
  gather_facts: no
  tasks:
  - name: ping
    ping:
  
  # From <https://docs.ansible.com/ansible/latest/user_guide/playbooks_loops.html> 
  - shell: "echo {{ item }}"
    loop:
      - "one"
      - "two"
    register: echo

  # show all the hosts in the current play
  # From <https://docs.ansible.com/ansible/latest/user_guide/playbooks_loops.html> 
  - debug:
      msg: "{{ item }}"
    loop: "{{ ansible_play_batch }}"

  # From <https://docs.ansible.com/ansible/latest/user_guide/playbooks_loops.html>
  - name: add several users
    when: foo is defined
    user:
      name: "{{ item.name }}"
      state: present
      groups: "{{ item.groups }}"
    loop:
      - { name: 'testuser1', groups: 'wheel' }
      - { name: 'testuser2', groups: 'root' }

  # https://docs.ansible.com/ansible/latest/user_guide/playbooks_loops.html#with-subelements
  - set_fact:
      objs: 
      - { name: 'testuser1', groups: ['wheel', 'root'] }
  - name: subelements
    debug: 
      msg: "{{ item.0.name }}{{ item.1 }}"
    loop: "{{ objs|subelements('groups') }}"
    ignore_errors: yes

  # https://docs.ansible.com/ansible/latest/user_guide/playbooks_loops.html#looping-over-inventory
  - name: Show all the hosts in the inventory
    debug:
      msg: "{{ item }}"
    loop: "{{ groups['all'] }}"
  - name: Show all the hosts in the current play
    debug:
      msg: "{{ item }}"
    loop: "{{ ansible_play_batch }}"