# https://docs.ansible.com/ansible/latest/user_guide/playbooks_strategies.html
---
- hosts: localhost
  gather_facts: no
  
  # Ansible would execute the play completely (all tasks) on serial number of the hosts before moving on to the next serial number hosts
  serial: 2

  # serial: "30%"

  # serial:
  #   - 1
  #   - 5
  #   - 10

  # serial:
  #   - "10%"
  #   - "20%"
  #   - "100%"

  # serial:
  #   - 1
  #   - 5
  #   - "20%"

  
  tasks:
  - name: ping
    ping:
    run_once: true
  - shell: pwd
    register: result
    