# Insert any of our icons directly into your HTML just by writing the code. Hosted by a production-scale CDN.

# From <https://img.icons8.com/> 
	
	
# FREE ICONS, PHOTOS, VECTORS, MUSIC, AND TOOLS

# From <https://icons8.com/> 



###
https://img.icons8.com/search

###
https://img.icons8.com/2266EE/search

###
https://img.icons8.com/color/search

###
https://img.icons8.com/color/flag