# https://www.mydailytutorials.com/ansible-create-directory/
---
- hosts: localhost
  gather_facts: no
  tasks:
  - name: ping
    ping:
  - name: Ansible Directory Creation example
    file:
      path: ansible_test1
      state: directory

  # Creating a local file using local_action statement
  - name: Ansible delete file example
    local_action:
      module: file
      path: ansible_test1/ansible_test1
      state: touch

  - name: Ansible delete multiple file example
    file:
      path: "{{ item }}"
      state: touch
    with_items:
      - ansible_test2.txt
      - ansible_test3.txt

  # https://stackoverflow.com/questions/50288543/how-to-use-wild-card-while-giving-file-permission-using-ansible
  - name: Find files
    find:
      paths: .
      patterns: "ansible_test2.txt"
    register: files_to_change
  - name: Modify the file permissions
    file:
      path: "{{ item.path }}"
      owner: "{{ ansible_user }}"
      group: "{{ ansible_user }}"
      mode: 755
    with_items: "{{ files_to_change.files }}"
