# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/get_url_module.html

---
- hosts: localhost
  gather_facts: no
  tasks:

  - get_url:
      url: https://cdn.jsdelivr.net/gh/octocat/Hello-World/README
      dest: ./temp_test