# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/git_module.html
---
- hosts: localhost
  gather_facts: no

  tasks:
  - name: ping
    ping:
  - name: git clone https://github.com/octocat/Hello-World.git temp_test.dir
    git:
      repo: 'https://github.com/octocat/Hello-World.git'
      dest: temp_test.dir

  # https://stackoverflow.com/questions/37841914/how-do-i-pass-username-and-password-while-using-ansible-git-module
  - name: ansible-playbook git.yml -e "githubuser=arbabname" -e "githubpassword=xxxxxxx" 
    git: 
      repo: "https://{{ githubuser | urlencode }}:{{ githubpassword | urlencode }}@github.com/octocat/Hello-World.git"
      dest: temp_test.dir
    when: githubuser is defined and githubpassword is defined