# https://docs.ansible.com/ansible/latest/modules/lineinfile_module.html
---
- hosts: localhost
  gather_facts: no

  tasks:
  - name: ping
    ping:

  - name: Insert path without converting \r\n
    lineinfile:
      create: yes
      path: "test.txt"
      regex: 'abcdefg'
      line: 123456