# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/setup_module.html
- hosts: localhost
  tasks:
  - name: Collect only facts returned by facter
    ansible.builtin.setup:
      gather_subset:
        - '!all'
        - '!any'
        - facter