---
# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/user_module.html
- hosts: localhost
  gather_facts: no
  tasks:
  - name: ping
    ping:
  - name: Ensure group "git" exists with correct gid
    ansible.builtin.group:
      name: git
      state: present
      gid: 1002
    become: yes
  - name: 
    ansible.builtin.user:
      name: git
      comment: Gitea
      uid: 1002
      group: git
    become: yes