# https://docs.ansible.com/ansible/latest/modules/wait_for_module.html
# https://stackoverflow.com/questions/57994127/how-do-i-read-in-a-file-from-ansible-and-get-it-to-return-the-last-few-lines
# https://stackoverflow.com/questions/42502809/regex-to-match-second-line

---
- hosts: localhost
  gather_facts: no

  tasks:
  - wait_for:
      path: README.md
      search_regex: '(?:\r\n?|\n){2}(.+)'
      timeout: 5
    register: line
  - set_fact:
      content: "{{ line.match_groups.0 }}"
  - debug: var=content