
---
- hosts: "{{ variable_host | default('localhost') }}"
  gather_facts: no
  vars:
    int_var: 123

  tasks:
  - name: ping
    ping:
  
  # https://stackoverflow.com/questions/33505521/how-to-use-arithmetic-when-setting-a-variable-value-in-ansible
  - debug:
      msg: "{{ int_var - 1 }}"