
---
- hosts: "{{ variable_host | default('localhost') }}"
  gather_facts: no
  vars:
    var1: "abcdefg"

  tasks:
  - name: ping
    ping:

  # https://stackoverflow.com/questions/39072079/how-can-i-dynamically-change-an-ansible-variable
  - set_fact:
      var2: "{{ var1 }}"

  # https://www.reddit.com/r/ansible/comments/c9v89g/replace_with_in_string_variable/
  - name: Replace
    debug:
      msg: "{{ var2 | replace('abc', \"123\") | regex_replace('[0-9]{2}', \"456\") }}"

  # https://serverfault.com/questions/907164/ansible-conditionally-define-variables-in-vars-file-if-a-certain-condition-is-m
  - set_fact:
      var3: "{{ 'a' if var1 is defined else 'b' }}"
  - debug: var=var3

  - set_fact:
      var4: "var3"
  - debug: var=var4

  # https://stackoverflow.com/questions/29276198/ansible-how-to-construct-a-variable-from-another-variable-and-then-fetch-its-v
  - set_fact:
      var5: "{{ lookup('vars', '{{ var4 }}') }}"
    ignore_errors: true
  - debug: var=var5
    when: var5 is defined