# https://docs.ansible.com/ansible/latest/modules/win_iis_webbinding_module.html
---
- hosts: localhost
  gather_facts: no

  tasks:
  - name: Add a HTTP binding on port 9090
    win_iis_webbinding:
      name: Default Web Site
      port: 9090
      state: present
  - name: Add a HTTPS binding
    win_iis_webbinding:
      name: Default Web Site
      protocol: https
      port: 443
      ip: "*"
      certificate_hash: 0123456789012345678901234567890123456789
      state: present