# https://docs.ansible.com/ansible/latest/modules/win_iis_webapppool_module.html
---
- hosts: localhost
  gather_facts: no

  tasks:
  - name: ping
    win_ping:
  - name: Return information about an existing application pool
    win_iis_webapppool:
      name: DefaultAppPool
      state: present