---
- hosts: localhost
  gather_facts: no

  tasks:
  - name: cert
    shell: openssl s_client -connect ifconfig.co:443 < /dev/null 2>/dev/null | openssl x509 -fingerprint -noout -in /dev/stdin
    register: output
  - set_fact:
      fingerprint: "{{ ( output.stdout ) | replace(':', '') | replace('SHA1 Fingerprint=', '') }}"
  - debug: var=fingerprint