# https://docs.ansible.com/ansible/latest/user_guide/playbooks_filters.html

---
- hosts: localhost
  gather_facts: no

  tasks:
  - debug: 
      msg: "{{ '%Y-%m-%d' | strftime }}"
  - debug: 
      msg: "{{ '%Y-%m-%d' | strftime(0) }}"          # => 1970-01-01
  - debug: 
      msg: "{{ '%Y-%m-%d' | strftime(1441357287) }}" # => 2015-09-04
  - debug: 
      msg: "{{ 102400000|human_readable }}"
  - debug: 
      msg: "{{ 102400000|to_uuid }}"
  - debug: 
      msg: "{{ 102400000|b64encode }}"
  - debug: 
      msg: "{{ 'MTAyNDAwMDAw'|b64decode }}"
  - debug: 
      msg: "{{ 'string.yml'|splitext }}"
  - name: "Human Readable"
    assert:
      that:
        - '"1.00 Bytes" == 1|human_readable'
        - '"1.00 bits" == 1|human_readable(isbits=True)'
        - '"10.00 KB" == 10240|human_readable'
        - '"97.66 MB" == 102400000|human_readable'
        - '"0.10 GB" == 102400000|human_readable(unit="G")'
        - '"0.10 Gb" == 102400000|human_readable(isbits=True, unit="G")'

  # https://stackoverflow.com/questions/45564899/extract-filename-from-file-result-in-ansible
  - debug: 
      msg: "{{ 'abc/string.yml' | basename }}"
  - debug: 
      msg: "{{ 'abc/string.yml' | dirname }}"
  - debug: 
      msg: "{{ 'abc/def' | basename }}"
  - debug: 
      msg: "{{ 'abc/def' | dirname }}"
  - debug: 
      msg: "{{ 'abc/' | basename }}"
  - debug: 
      msg: "{{ 'abc/' | dirname }}"
  - debug: 
      msg: "{{ 'abc/string.yml' | realpath }}"
  - debug: 
      msg: "{{ 'abc/string.yml' | relpath }}"