# https://docs.ansible.com/ansible/latest/collections/ansible/windows/win_user_right_module.html

# The name of the User Right as shown by the Constant Name value from:
# https://technet.microsoft.com/en-us/library/dd349804.aspx


---
- hosts: localhost
  gather_facts: no

  tasks:
  - name: ping
    win_ping:

  - name: Add account to Log on as a service
    win_user_right:
      name: SeServiceLogonRight
      users:
      - .\Administrator
      - '{{ansible_hostname}}\local-user'
      action: add

# How to assign a user “Batch Job Rights” Locally
# https://www.urtech.ca/2019/06/solved-this-task-requires-that-the-user-account-specified-has-log-on-as-batch-job-rights/
# Security Settings > Local Policies > User Rights Assignment node
  - name: SeBatchLogonRight
    win_user_right:
      name: SeBatchLogonRight
      users:
      - .\Administrator
      action: add