# https://docs.ansible.com/ansible/latest/collections/ansible/windows/win_optional_feature_module.html
# https://hahndorf.eu/blog/WindowsFeatureViaCmd

---
- hosts: localhost
  gather_facts: no

  tasks:
  - name: ping
    win_ping:
  - name: Install Microsoft Subsystem for Linux
    win_optional_feature:
      name: Microsoft-Windows-Subsystem-Linux
      state: present
    register: wsl_status

  - name: Enable TelnetClient
    win_optional_feature:
      name: TelnetClient
      state: present

  - name: reboot_required
    block:
      - name: "win_reboot if reboot_required"
        debug:
          msg: "wsl_status"

      # - win_reboot:
    when: wsl_status.reboot_required