# https://docs.ansible.com/ansible/latest/modules/win_feature_module.html
---
- hosts: localhost
  gather_facts: no

  tasks:
  - name: ping
    win_ping:
  - name: Enable WSL
    win_feature:
      name: Microsoft-Windows-Subsystem-Linux
      state: present
    register: win_feature

  - name: reboot_required
    block:
      - name: "win_reboot if reboot_required"
        debug:
          msg: "win_reboot"

      # - win_reboot:
    when: win_feature.reboot_required