# https://docs.ansible.com/ansible/latest/collections/community/windows/win_scheduled_task_module.html
---
- hosts: localhost
  gather_facts: no

  tasks:
  - name: ping
    win_ping:

  - name: Create a task to open 2 command prompts as SYSTEM
    tags: present
    win_scheduled_task:
      name: TaskName
      description: open command prompt
      actions:
      - path: cmd.exe
        arguments: /c hostname
      - path: cmd.exe
        arguments: /c whoami
      triggers:
      - type: daily
        start_boundary: '2017-10-09T22:00:00'
        repetition:
          interval: PT60M
          duration: PT1440M
      username: SYSTEM
      state: present
      enabled: yes
      run_level: highest
      disallow_start_if_on_batteries: no
      wake_to_run: yes
      
  - name: Change above task to run under a user account, storing the passwords
    win_scheduled_task:
      name: TaskName
      username: a
      password: 1
      logon_type: password

  - name: Remove task
    tags: absent
    win_scheduled_task:
      name: TaskName
      state: absent