# https://docs.ansible.com/ansible/latest/modules/win_shell_module.html
---
- hosts: localhost
  gather_facts: no

  tasks:
  - name: win_shell
    win_shell: echo %cd%
    args:
      executable: cmd
    register: cmd_out

  - win_shell: "wsl wslpath -w {{ playbook_dir }}"
    register: p

  - set_fact:
      cmd: "{{ p.stdout_lines.0 }}\\web_request.ps1"
  - debug: var=cmd

  - win_shell: "{{ cmd }} https://ifconfig.co/json"
    register: cmd_out
  - debug: var=cmd_out.stdout_lines