# https://docs.ansible.com/ansible/latest/modules/win_ping_module.html
---
- hosts: localhost
  gather_facts: no

  tasks:
  - name: ping
    win_ping:

  - debug: 
      msg: "{{ playbook_dir }}"

  - win_shell: "wsl wslpath -w {{ playbook_dir }}"
    register: p

  - debug: var=p.stdout_lines