---
- hosts: localhost
  gather_facts: no
  tasks:
  - name: ping
    tags: test
    ping:
  - shell: pwd
    register: result
  - debug: var=result.stdout_lines
  - debug: var=ansible_python_interpreter
  - debug: var=ansible_playbook_python