# ansible-playbook host.yml --extra-vars "variable_host=test"
# Override hosts variable of Ansible playbook from the command line
# From <https://stackoverflow.com/questions/33222641/override-hosts-variable-of-ansible-playbook-from-the-command-line> 

# ansible-playbook variables.yml --extra-vars "version=1.23.45 other_variable=foo"
# ansible-playbook variables.yml -e firstvar=false -e second_var=value2
# From <https://stackoverflow.com/questions/30662069/how-can-i-pass-variable-to-ansible-playbook-in-the-command-line>

---
- hosts: "{{ variable_host | default('localhost') }}"
  gather_facts: no
  vars:
    var1: "abcdefg"
    my_version: "{{ version }}"
    my_other_variable: "{{ other_variable }}"

    # From <https://stackoverflow.com/questions/21422158/ansible-accessing-local-environment-variables> 
    path: "{{ lookup('env', 'PATH') }}"
    home: "{{ lookup('env', 'HOME') }}"
    int_var: 123
    
  tasks:
  - name: ping
    ping:

  # https://www.toptechskills.com/ansible-tutorials-courses/ansible-include-import-variables-tutorial-examples/
  - include_vars: vars.yml

  # Special Variables
  # From <https://docs.ansible.com/ansible/latest/reference_appendices/special_variables.html>
  - debug: var=inventory_hostname # The inventory name for the ‘current’ host being iterated over in the play
  - debug: var=ansible_play_batch # List of active hosts in the current play run limited by the serial, aka ‘batch’. Failed/Unreachable hosts are not considered ‘active’.
  - debug: var=ansible_play_hosts_all # List of all the hosts that were targeted by the play
  - debug: var=ansible_version # List of all the hosts that were targeted by the play
  - debug: var=ansible_user # The user Ansible ‘logs in’ as
  - debug: var=ansible_host # The ip/name of the target host to use instead of inventory_hostname
  - debug: var=ansible_connection # The connection plugin actually used for the task on the target host
  - debug: var=ansible_playbook_python # The path to the python interpreter being used by Ansible on the controller
  - debug: var=ansible_python_interpreter # The path to the Python executable Ansible should use on the target host

  - debug: var=home
  - debug: var=path

  # Get current target host's IP address
  # https://stackoverflow.com/questions/39819378/ansible-get-current-target-hosts-ip-address
  - debug: var=ansible_ssh_host

  # https://stackoverflow.com/questions/30787273/variable-that-has-the-path-to-the-current-ansible-playbook-that-is-executing
  - debug: var=playbook_dir

  - debug: var=version
  - debug: var=other_variable

  # https://stackoverflow.com/questions/39072079/how-can-i-dynamically-change-an-ansible-variable
  - set_fact:
      var2: "{{ var1 }}"

  # https://www.reddit.com/r/ansible/comments/c9v89g/replace_with_in_string_variable/
  - name: Replace
    debug:
      msg: "{{ var2 | replace('abc', \"123\") | regex_replace('[0-9]{2}', \"456\") }}"

  - shell: "echo {{ firstvar }}"
    register: result1
    when: firstvar is defined
  - debug: var=result1.stdout_lines
  - shell: "echo {{ second_var }}"
    register: result2
    when: second_var is defined
  - debug: var=result2.stdout_lines
  
  # https://stackoverflow.com/questions/33505521/how-to-use-arithmetic-when-setting-a-variable-value-in-ansible
  - debug:
      msg: "{{ int_var - 1 }}"

  # https://serverfault.com/questions/907164/ansible-conditionally-define-variables-in-vars-file-if-a-certain-condition-is-m
  - set_fact:
      var3: "{{ 'a' if var1 is defined else 'b' }}"
  - debug: var=var3

  - set_fact:
      var4: "var3"
  - debug: var=var4

  # https://stackoverflow.com/questions/29276198/ansible-how-to-construct-a-variable-from-another-variable-and-then-fetch-its-v
  - set_fact:
      var5: "{{ lookup('vars', '{{ var4 }}') }}"
    ignore_errors: true
  - debug: var=var5
    when: var5 is defined

  # https://stackoverflow.com/questions/28709501/how-to-list-all-currently-targeted-hosts-in-an-ansible-play
  - debug: msg="play_hosts={{play_hosts}}"
    run_once: true
