@startuml HelloWorld

skinparam linetype ortho

rectangle "PlantUML" {
    rectangle hello  [
        Hello <size:16><&musical-note></size>
    ]
    rectangle "World<size:16><&globe></size>" as world
    hello ~r~> world: h
    hello -r- world: i
}

@enduml