### https://ifconfig.co

### https://github.com/mpolden/echoip


### JSON output
http://ifconfig.co/json

### Plain output
http://ifconfig.co/ip

### Port testing
http://ifconfig.co/port/8080

### ASN lookup
http://ifconfig.co/asn

### Country lookup
http://ifconfig.co/country

### Country lookup
http://ifconfig.co/country-iso