# This is a basic workflow to help you get started with Actions

name: Test

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    # https://damienaicheh.github.io/github/actions/2022/01/20/set-dynamic-parameters-github-workflows-en.html
    inputs:
      abc:
        description: 'abc.'
        required: true
        default: '1'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: [ ubuntu-latest ]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world! ${{ github.event.inputs.abc }}

      # Runs a set of commands using the runners shell
      # https://stackoverflow.com/questions/59073850/github-actions-get-url-of-test-build
      - name: Run a multiple-lines script
        run: |
          echo ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
      
      # https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#adding-a-job-summary
      - name: GITHUB_STEP_SUMMARY
        run: echo "### Hello world! :rocket:" >> $GITHUB_STEP_SUMMARY

      # https://github.com/actions/upload-release-asset/issues/47
      - name: Generate variables
        run: |
          ARTIFACT_PATHNAME=$(ls * | head -n 1)
          echo "ARTIFACT_PATHNAME=${ARTIFACT_PATHNAME}" >> $GITHUB_ENV

      - name: echo ARTIFACT_PATHNAME
        env:
          ARTIFACT_PATHNAME: ${{ env.ARTIFACT_PATHNAME }}
        run: |
          echo ARTIFACT_PATHNAME
          echo $ARTIFACT_PATHNAME
          
      # https://github.com/marketplace/actions/hello-world-js
      - uses: gr2m/hello-world-js-action@v1.x
        with:
          greeting: ${{ env.ARTIFACT_PATHNAME }}